config/routes.rb
Buzzertoby::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  devise_for :users
  
  resources :cards

  resources :decks

  

  

end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :deck
  acts_as_taggable
  before_save :ajouter_tags

  def valeur_enum
    ['1','2','3','4','5','6','7','8','9','10','V','D','R']
  end
  
  def couleur_enum
    ['♥', '♠', '♦', '♣']
  end
  
  def ajouter_tags
    case self.couleur
      when '♦','♥'
        self.tag_list.add("rouge")
      when '♠','♣'
        self.tag_list.add("noire")
    end
    case self.valeur
      when '1','3','5','7','9'
        self.tag_list.add("paire")
      when '2','4','6','8','10'
        self.tag_list.add("impaire")
      when 'V','D','R'
        self.tag_list.add("figure")
    end
  end
  
end

app/models/deck.rb
class Deck < ActiveRecord::Base
  has_many :cards
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  
  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render action: 'show', status: :created, location: @card }
      else
        format.html { render action: 'new' }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:name, :couleur, :valeur, :deck_id, :tag_list)
    end
end



    

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :set_deck, only: [:show, :edit, :update, :destroy]

  # GET /decks
  # GET /decks.json
  def index
    @decks = Deck.all
  end

  # GET /decks/1
  # GET /decks/1.json
  def show
  end

  # GET /decks/new
  def new
    @deck = Deck.new
  end

  # GET /decks/1/edit
  def edit
  end

  # POST /decks
  # POST /decks.json
  def create
    @deck = Deck.new(deck_params)

    respond_to do |format|
      if @deck.save
        format.html { redirect_to @deck, notice: 'Deck was successfully created.' }
        format.json { render action: 'show', status: :created, location: @deck }
      else
        format.html { render action: 'new' }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /decks/1
  # PATCH/PUT /decks/1.json
  def update
    respond_to do |format|
      if @deck.update(deck_params)
        format.html { redirect_to @deck, notice: 'Deck was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /decks/1
  # DELETE /decks/1.json
  def destroy
    @deck.destroy
    respond_to do |format|
      format.html { redirect_to decks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deck
      @deck = Deck.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deck_params
      params.require(:deck).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
    
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/views/cards/_form.html.erb
<%= form_for(@card) do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% @card.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :couleur %><br>
    <%= f.text_field :couleur %>
  </div>
  <div class="field">
    <%= f.label :valeur %><br>
    <%= f.text_field :valeur %>
  </div>
  <div class="field">
    <%= f.label :deck_id %><br>
    <%= f.number_field :deck_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing card</h1>

<%= render 'form' %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<span class="soluce"></span>
<h1>Jeu de cartes</h1>
Constituer l'évènement suivant (en glissant les cartes le constituant sur le tapis vert) :
<button id="random">random</button>
<div>
    <input type="radio" name="conjonction" value="et" checked>et</input>
    <input type="radio" name="conjonction" value="ou">ou</input>
</div>
<div>
    <input type="checkbox" name="un coeur" data-couleur="♥">un coeur</input>
	<input type="checkbox" name="un pique" data-couleur="♠">un pique</input>
	<input type="checkbox" name="un carreau" data-couleur="♦">un carreau</input>
	<input type="checkbox" name="un trèfle" data-couleur="♣">un trèfle</input>
	<input type="checkbox" name="une rouge" data-tags="rouge">une rouge</input>
	<input type="checkbox" name="une noire" data-tags="noire">une noire</input>
	<input type="checkbox" name="un valet" data-valeur="V">un valet</input>
	<input type="checkbox" name="une dame" data-valeur="D">une dame</input>
	<input type="checkbox" name="un roi" data-valeur="R">un roi</input>
	<input type="checkbox" name="un as" data-valeur="1">un as</input>
	<input type="checkbox" name="une figure" data-tags="figure">une figure</input>
	<input type="checkbox" name="un pair" data-tags="paire">paire</input>
	<input type="checkbox" name="un impair" data-tags="impaire">impaire</input>
</div>
    
    
<h2>La carte tirée au hasard est un <span class="evenement_aleatoire" /></span></h2>

<div id="progressbar"></div>

<div class="ensemble" id="banque">
	<% @cards.each do |card| %>
	  <div class="carte <%= card.couleur %>" id="carte_<%= card.id %>" data-tags="<%= card.tag_list %>" data-valeur="<%= card.valeur %>" data-couleur="<%= card.couleur %>"><%= card.valeur %><%= card.couleur %></div>
	<% end %>
</div>
<br />
<div id="evenement" class="ensemble"></div>

<h4>L'évènement {<span class="listeEventualites"></span>} <span class="diagnostic">ne correspond pas</span> à l'évènement 
"la carte est <span class="evenement_aleatoire"></span>".
<br />
<h1>Listing cards</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Couleur</th>
      <th>Valeur</th>
      <th>Deck</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= card.name %></td>
        <td><%= card.couleur %></td>
        <td><%= card.valeur %></td>
        <td><%= card.deck_id %></td>
        <td><%= link_to 'Show', card %></td>
        <td><%= link_to 'Edit', edit_card_path(card) %></td>
        <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Card', new_card_path %>

app/views/cards/new.html.erb
<h1>New card</h1>

<%= render 'form' %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @card.name %>
</p>

<p>
  <strong>Couleur:</strong>
  <%= @card.couleur %>
</p>

<p>
  <strong>Valeur:</strong>
  <%= @card.valeur %>
</p>

<p>
  <strong>Deck:</strong>
  <%= @card.deck_id %>
</p>

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>

app/views/decks/_form.html.erb
<%= form_for(@deck) do |f| %>
  <% if @deck.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deck.errors.count, "error") %> prohibited this deck from being saved:</h2>

      <ul>
      <% @deck.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/decks/edit.html.erb
<h1>Editing deck</h1>

<%= render 'form' %>

<%= link_to 'Show', @deck %> |
<%= link_to 'Back', decks_path %>

app/views/decks/index.html.erb
<h1>Listing decks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @decks.each do |deck| %>
      <tr>
        <td><%= deck.name %></td>
        <td><%= link_to 'Show', deck %></td>
        <td><%= link_to 'Edit', edit_deck_path(deck) %></td>
        <td><%= link_to 'Destroy', deck, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Deck', new_deck_path %>

app/views/decks/new.html.erb
<h1>New deck</h1>

<%= render 'form' %>

<%= link_to 'Back', decks_path %>

app/views/decks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @deck.name %>
</p>

<%= link_to 'Edit', edit_deck_path(@deck) %> |
<%= link_to 'Back', decks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Buzzertoby</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>